export const rotations: RotationPreset[] = [];
export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Electro Heart of Sworn Vigil Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Skill, 100 ATK, 18.4% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ReminiscenceSuhsintheInevitable","echoSet":"HeartofSwornVigil","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceSkillDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"Soulfrayer","echoSet":"HeartofSwornVigil","stat":"Electro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceSkillDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"Formrender","echoSet":"HeartofSwornVigil","stat":"Electro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"3":{"type":1,"echo":"FogLionarchHead","echoSet":"HeartofSwornVigil","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"4":{"type":1,"echo":"JadeNetherSerpent","echoSet":"HeartofSwornVigil","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"ReminiscenceSuhsintheInevitable","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Electro Heart of Sworn Vigil Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Skill, 100 ATK, 18.4% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ReminiscenceSuhsintheInevitable","echoSet":"HeartofSwornVigil","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceSkillDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"Soulfrayer","echoSet":"HeartofSwornVigil","stat":"Electro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceSkillDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"Formrender","echoSet":"HeartofSwornVigil","stat":"Electro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"3":{"type":1,"echo":"JadeNetherSerpent","echoSet":"HeartofSwornVigil","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"BloomburstPuppet","echoSet":"HeartofSwornVigil","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50}},"mainEcho":{"echo":"ReminiscenceSuhsintheInevitable","rank":5}}
    }
];
