export const resonanceChains = [
  {
    key: `SequenceNode1ABoatToCrossTheRisingTide`,
    name: `Sequence Node 1: A Boat to Cross the Rising Tide`,
    details: `<div>Casting <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Formshift</span> grants Hsin 2 stacks of <span style="color:#ffd12f;" class="font-bold">Radiance Ward</span>, stacking up to 2 times. Switching to <span style="color:#ffd12f;" class="font-bold">Answering Form</span> clears all stacks. When Hsin takes DMG from an enemy target's attack, 1 stack of <span style="color:#ffd12f;" class="font-bold">Radiance Ward</span> can be consumed to make Her immune to interruption and reduce DMG taken by 60% for 1s. This effect can be triggered once every 1s.<br><br>While in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Electro Flare</span>:<br>When Hsin enters combat, if <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131113">Heart of Thunder</span></span> is below 50 stacks, it is increased to 50 stacks, triggered once every 12s.<br>The DMG Multiplier of the <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="850013">Electro Flare</span></span> DMG triggered by <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Heartward by Moon</span> is increased to 42% x (the number of <span style="color:#ffd12f;" class="font-bold">Heart of Thunder</span> stacks on Hsin) x (the <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="850013">Electro Flare</span></span> DMG Multiplier corresponding to the target's current <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="850013">Electro Flare</span></span> stacks).</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM1_UI.webp`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode1ABoatToCrossTheRisingTideUnison`,
    name: `Sequence Node 1: A Boat to Cross the Rising Tide (Unison)`,
    stance: "Unison",
    details: `<div>While in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Unison</span>:<br>The DMG Multipliers of <span style="color:#ffd12f;" class="font-bold">Intro Skill - Answering Form: Manifold Unison</span> and <span style="color:#ffd12f;" class="font-bold">Intro Skill - Illumining Form: Manifold Unison</span> are increased by 15%, and each stack of <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131111">Unison Boon</span></span> additionally increases the DMG Multipliers of <span style="color:#ffd12f;" class="font-bold">Intro Skill - Answering Form: Manifold Unison</span> and <span style="color:#ffd12f;" class="font-bold">Intro Skill - Illumining Form: Manifold Unison</span> by 10%, up to a total of 4 stacks.</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM1_UI.webp`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: [
          "IntroSkillAnsweringFormManifoldUnisonDMG",
          "IntroSkillIlluminingFormManifoldUnisonDMG",
        ],
        modifierValue: 0.15,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode2ToWakeIsToWonderWhatIAm`,
    name: `Sequence Node 2: To Wake Is to Wonder What I Am`,
    details: `<div>The DMG Multipliers of <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Answering Form: Realm Wanderer</span> and <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Answering Form: Realm Protector</span> are increased by 60%.<br>The DMG Multipliers of <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Illumining Form: Beholding All Horizons</span> and <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Illumining Form: Stilling All Horizons</span> are increased by 60%.<br><br>When Hsin enters combat, reset the Cooldowns for Hsin to gain <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131114">Resolution of Wishes</span></span> and <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131115">Law of Heaven</span></span>, and restore 100 additional points of <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131117">Answering Heart</span></span>. This effect can be triggered once every 12s.</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM2_UI.webp`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: [
          "HeavyAttackAnsweringFormRealmWandererDMG",
          "HeavyAttackAnsweringFormRealmProtectorDMG",
          "HeavyAttackIlluminingFormBeholdingAllHorizonsDMG",
          "HeavyAttackIlluminingFormStillingAllHorizonsDMG",
        ],
        modifierValue: 0.6,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode3ADreamOfReturnAmongTheHills`,
    name: `Sequence Node 3: A Dream of Return Among the Hills`,
    details: `<div>The DMG Multiplier of <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Pillars Across Heaven</span> is increased by 70%.</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM3_UI.webp`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["PillarsAcrossHeavenDMG"],
        modifierValue: 0.7,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode3ADreamOfReturnAmongTheHillsUnison`,
    name: `Sequence Node 3: A Dream of Return Among the Hills (Unison)`,
    stance: "Unison",
    details: `<div>While in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Unison</span>:<br>The Crit. DMG of <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Pillars Across Heaven</span> is increased by 20%, and each stack of <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131111">Unison Boon</span></span> additionally increases its Crit. DMG by 15%, up to a total of 4 stacks.</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM3_UI.webp`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifySpecificTalents: ["PillarsAcrossHeavenDMG"],
        modifierValue: 0.2,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode3ADreamOfReturnAmongTheHillsElectroFlare`,
    name: `Sequence Node 3: A Dream of Return Among the Hills (Electro Flare)`,
    stance: "Electro Flare",
    details: `<div>While in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Electro Flare</span>:<br>When the last stage of <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Pillars Across Heaven</span> hits a target inflicted with <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="850013">Electro Flare</span></span>, it triggers 1 instance of <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="850013">Electro Flare</span></span> DMG, with its DMG Multiplier equal to 1500% times the <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="850013">Electro Flare</span></span> DMG Multiplier corresponding to the current <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="850013">Electro Flare</span></span> stacks on the target.</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM3_UI.webp`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "EnableAttack",
        modifierValue: ["SequenceNode3ADreamOfReturnAmongTheHillsElectroFlare"],
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode4ARiverOfLanternsARiverOfWishes`,
    name: `Sequence Node 4: A River of Lanterns, a River of Wishes`,
    details: `<div>All Resonators in the team gain 20% All-Attribute DMG Bonus for 30s when a Resonator in the team triggers any of the following actions:<br>- Inflict <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="850013">Electro Flare</span></span> or <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="150806">Electro Rage</span></span> on a target.<br>- Gain <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131110">Unison</span></span> while not having the effect.<br>- Trigger <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131112">Unison Response</span></span>.</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM4_UI.webp`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "AllElementAttributeBonus",
        modifierValue: 0.2,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode5FormsTurnAsTheHeartWills`,
    name: `Sequence Node 5: Forms Turn as the Heart Wills`,
    details: `<div>While in <span style="color:#ffd12f;" class="font-bold">Illumining Form</span>, DMG taken by Hsin is reduced by 20%.<br>When Hsin takes a fatal blow, She will not be knocked out, but instead restores 100% of Max HP and becomes immune to DMG and interruption for 1s. This effect can be triggered once every 10 minute.</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM5_UI.webp`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode6TheMoonOwesItsLightToTheLiving`,
    name: `Sequence Node 6: The Moon Owes Its Light to the Living`,
    details: `<div>Targets take 40% more Resonance Skill DMG from Hsin.<br><br>Resonance Skill DMG dealt by Hsin ignores 20% of the target's DEF.</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM6_UI.webp`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "specialMultiplier",
        modifySpecificTalents: [
          "ResonanceSkillAnsweringFormDMG",
          "ResonanceSkillIlluminingFormDMG",
          "HeavyAttackAnsweringFormRealmWandererDMG",
          "HeavyAttackAnsweringFormRealmProtectorDMG",
          "HeavyAttackIlluminingFormBeholdingAllHorizonsDMG",
          "HeavyAttackIlluminingFormStillingAllHorizonsDMG",
          "ResonanceSkillIlluminingFormPillarsAlignedDMG",
          "PillarsAcrossHeavenDMG",
          "IntroSkillAnsweringFormManifoldUnisonDMG",
          "IntroSkillIlluminingFormManifoldUnisonDMG",
        ],
        modifierValue: 0.4,
      },
      {
        modifier: "DEFIgnore",
        modifySpecificTalents: [
          "ResonanceSkillAnsweringFormDMG",
          "ResonanceSkillIlluminingFormDMG",
          "HeavyAttackAnsweringFormRealmWandererDMG",
          "HeavyAttackAnsweringFormRealmProtectorDMG",
          "HeavyAttackIlluminingFormBeholdingAllHorizonsDMG",
          "HeavyAttackIlluminingFormStillingAllHorizonsDMG",
          "ResonanceSkillIlluminingFormPillarsAlignedDMG",
          "PillarsAcrossHeavenDMG",
          "IntroSkillAnsweringFormManifoldUnisonDMG",
          "IntroSkillIlluminingFormManifoldUnisonDMG",
        ],
        modifierValue: 0.2,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode6TheMoonOwesItsLightToTheLivingUnison`,
    name: `Sequence Node 6: The Moon Owes Its Light to the Living (Unison)`,
    stance: "Unison",
    details: `<div>While in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Unison</span>:<br>The maximum stacks of the <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131111">Unison Boon</span></span> effect on Resonators in the team are additionally increased by 1. When a Resonator in the team triggers <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131112">Unison Response</span></span>, all Resonators in the team additionally gain 1 stack of <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="131111">Unison Boon</span></span> for 30s. This effect does not stack.</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM6_UI.webp`,
    hasStacks: false,
    // The +1 Unison Boon max stacks is applied in effectiveBuffStacks.ts.
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode6TheMoonOwesItsLightToTheLivingElectroFlare`,
    name: `Sequence Node 6: The Moon Owes Its Light to the Living (Electro Flare)`,
    stance: "Electro Flare",
    details: `<div>While in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Electro Flare</span>:<br>While in combat, <span style="color:#ffd12f;" class="font-bold"><span class="term-reference-link " data-term-id="850013">Electro Flare</span></span> DMG taken by targets within a certain range around Hsin can be Critical, with Crit. Rate fixed at 80% and Crit. DMG fixed at 230%.</div>`,
    icon: `https://static.nanoka.cc/assets/ww/UIResources/Common/Image/IconDevice/T_IconDevice_XinM6_UI.webp`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifySpecificTalents: [
          "ElementalEffectElectroFlare",
          "HeartOfThunderInstantDMG",
          "HeartOfThunderDelayedDMG",
          "SequenceNode3PillarsAcrossHeavenElectroFlareDMG",
        ],
        modifierValue: 0.8,
      },
      {
        modifier: "CritDMG",
        modifySpecificTalents: [
          "ElementalEffectElectroFlare",
          "HeartOfThunderInstantDMG",
          "HeartOfThunderDelayedDMG",
          "SequenceNode3PillarsAcrossHeavenElectroFlareDMG",
        ],
        // total 230% = 100% base + 130%, matching the existing +1 base
        // convention in attacks.ts's ElectroFlare crit dispatch
        modifierValue: 1.3,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  }
];
