// Regenerate everything the /rankings page derives from the wuwa_calc submodule:
//   src/sim/skittle.css        Riley's stylesheet, every selector scoped under .skittle-root
//   public/dist/solves/*.json  his precomputed solves (the page fetches ./dist/solves/… relative to /rankings)
//   public/sim/loading.gif     the loading overlay sticker
// Run after `git -C vendor/wuwa_calc pull`:   node scripts/skittle-sync.mjs
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync, copyFileSync } from "node:fs";
import { execSync } from "node:child_process";
import postcss from "postcss";

const SUB = "vendor/wuwa_calc";
const commit = execSync("git rev-parse --short HEAD", { cwd: SUB }).toString().trim();
const ROOT = ".skittle-root";
// selectors for elements Riley appends to document.body — they must stay global
const GLOBAL = [/^\.pop\b/, /^\.ctxmenu\b/, /^body\.coldrag/];
// ...and what he renders INSIDE those (the DPR breakdown's `.rtable` grid, `.gear`/`.stat` tables, `.cols`)
// is styled by the same generic rules as the page, so every scoped rule also applies under them
const HOSTS = [ROOT, ".pop", ".ctxmenu"];

function scope(sel) {
  const s = sel.trim();
  if (GLOBAL.some((re) => re.test(s))) return s;
  if (s.startsWith(":root")) return s.replace(":root", ROOT);
  if (/^html\b/.test(s)) return s.replace(/^html/, ROOT);
  if (/^body\b/.test(s)) return s.replace(/^body/, ROOT);
  return HOSTS.map((host) => `${host} ${s}`).join(", ");
}

// Riley moved his stylesheet and loading sticker from resources/ to the repo root in Sept 2026
const pick = (...paths) => paths.find((f) => existsSync(f)) ?? paths[0];
const CSS_PATH = pick(`${SUB}/index.css`, `${SUB}/resources/index.css`);
const GIF_PATH = pick(`${SUB}/loading.gif`, `${SUB}/resources/loading.gif`);
// ...and his shipped solves from tests/solves/ to dist/solves/ (d5a147e), which his page now fetches
const SOLVES = pick(`${SUB}/dist/solves`, `${SUB}/tests/solves`);
const SOLVES_OUT = SOLVES.endsWith("dist/solves") ? "public/dist/solves" : "public/tests/solves";
const css = readFileSync(CSS_PATH, "utf8");
const root = postcss.parse(css);
let rules = 0;
root.walkRules((rule) => {
  if (rule.parent?.type === "atrule" && /keyframes$/.test(rule.parent.name)) return;
  rule.selectors = rule.selectors.map(scope);
  rules++;
});
const header = `/* GENERATED by scripts/skittle-sync.mjs from vendor/wuwa_calc@${commit} (${CSS_PATH.replace(`${SUB}/`, "")}) — do not edit.
   Riley31415/wuwa_calc, ISC. Every selector is scoped under ${ROOT} (and repeated under .pop / .ctxmenu, whose
   contents share the page's rules); .pop / .ctxmenu / body.coldrag themselves stay global because his code
   appends those to document.body. */\n`;
writeFileSync("src/sim/skittle.css", header + root.toString());

mkdirSync(SOLVES_OUT, { recursive: true });
let files = 0;
for (const f of readdirSync(SOLVES)) {
  if (f.endsWith(".json")) { copyFileSync(`${SOLVES}/${f}`, `${SOLVES_OUT}/${f}`); files++; }
}
mkdirSync("public/sim", { recursive: true });
copyFileSync(GIF_PATH, "public/sim/loading.gif");
console.log(`skittle-sync: wuwa_calc@${commit}: ${rules} CSS rules scoped -> src/sim/skittle.css, ${files} solve files -> ${SOLVES_OUT}/, loading.gif -> public/sim/`);
