// Regenerate everything the /rankings page derives from the wuwa_calc submodule:
//   src/sim/skittle.css        Riley's stylesheet, every selector scoped under .skittle-root
//   public/tests/solves/*.json his precomputed solves (the page fetches ./tests/solves/… relative to /rankings)
//   public/sim/loading.gif     the loading overlay sticker
// Run after `git -C vendor/wuwa_calc pull`:   node scripts/skittle-sync.mjs
import { readFileSync, writeFileSync, mkdirSync, readdirSync, copyFileSync } from "node:fs";
import { execSync } from "node:child_process";
import postcss from "postcss";

const SUB = "vendor/wuwa_calc";
const commit = execSync("git rev-parse --short HEAD", { cwd: SUB }).toString().trim();
const ROOT = ".skittle-root";
// selectors for elements Riley appends to document.body — they must stay global
const GLOBAL = [/^\.pop\b/, /^\.ctxmenu\b/, /^body\.coldrag/];

function scope(sel) {
  const s = sel.trim();
  if (GLOBAL.some((re) => re.test(s))) return s;
  if (s.startsWith(":root")) return s.replace(":root", ROOT);
  if (/^html\b/.test(s)) return s.replace(/^html/, ROOT);
  if (/^body\b/.test(s)) return s.replace(/^body/, ROOT);
  return `${ROOT} ${s}`;
}

const css = readFileSync(`${SUB}/resources/index.css`, "utf8");
const root = postcss.parse(css);
let rules = 0;
root.walkRules((rule) => {
  if (rule.parent?.type === "atrule" && /keyframes$/.test(rule.parent.name)) return;
  rule.selectors = rule.selectors.map(scope);
  rules++;
});
const header = `/* GENERATED by scripts/skittle-sync.mjs from vendor/wuwa_calc@${commit} (resources/index.css) — do not edit.
   Riley31415/wuwa_calc, ISC. Every selector is scoped under ${ROOT}; .pop / .ctxmenu / body.coldrag stay global
   because his code appends those to document.body. */\n`;
writeFileSync("src/sim/skittle.css", header + root.toString());

mkdirSync("public/tests/solves", { recursive: true });
let files = 0;
for (const f of readdirSync(`${SUB}/tests/solves`)) {
  if (f.endsWith(".json")) { copyFileSync(`${SUB}/tests/solves/${f}`, `public/tests/solves/${f}`); files++; }
}
mkdirSync("public/sim", { recursive: true });
copyFileSync(`${SUB}/resources/loading.gif`, "public/sim/loading.gif");
console.log(`skittle-sync: wuwa_calc@${commit}: ${rules} CSS rules scoped -> src/sim/skittle.css, ${files} solve files -> public/tests/solves/, loading.gif -> public/sim/`);
